### ISSUE TITLE
The photo appears to snap back/zoom out when the card preview is generated?

### ISSUE THREAD

**Issue by granthleslie** [sellry/cardfool-issues#26] opened 2015-11-06 15:26 UTC
If you upload a photo to a photo card and zoom/rotate the photo to fit, when you click 'next' to preview the card you've made...the photo snaps back into how it originally came into the image_area.  

I'm using an iPhone 5.

**Comment by cindysamco** [comment] 2015-11-06 19:41
Duplicate of #15

**Closed** 2015-11-06 19:42 UTC
Labels: duplicate
